logger:
    format: json
    debug: true
storage:
    method: 'bolt'
global:
    sslcert: 'cert.pem' 
    sslkey: 'key.pem'
    dns: 'discovery.local.uspeak.io'
hooks:
    preadd: 'http://localhost:5000/handle'
web:
    api:
        adminenabled: true
