# Compile with
# CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags '-s' -o uspeakd-static *.go
---
- hosts: nodes
  gather_facts: yes
  remote_user: root
  vars:
      LOG_FORMAT: 'json'
      ansible_ssh_private_key_file: "~/.ssh/uspeak_ed25519"
      admin_enabled: true
      admin_user: 'admin'
      hook_preadd: 'https://monitor.uspeak.io/handle'
  tasks:
  - name: disable selinux
    selinux:
      state: disabled
  - name: install epel
    yum:
      name: epel-release
      state: latest
  - name: install nginx
    package:
      name: nginx
      state: latest
  - name: install git
    package:
      name: git
      state: latest
  - name: create deployment directory
    file:
      path: /opt/uspeak
      state: directory
  - name: create data directory
    file:
      path: /var/lib/uspeak/data
      state: directory
  - name: create configuration directory
    file:
      path: /etc/uspeak
      state: directory
  - name: write config file
    template:
      src: ansible/config.yml.j2
      dest: /etc/uspeak/config.yml
  - name: copy ssl certificate
    copy:
      src: cert.pem
      dest: '/etc/uspeak/cert.pem'
  - name: copy ssl key
    copy:
      src: key.pem
      dest: '/etc/uspeak/key.pem'
  - name: copy the uspeakd-static binary
    copy:
      src: uspeakd-static
      dest: '/opt/uspeak/uspeakd'
      force: yes
      mode: 0755
  - name: update service file
    copy:
      src: 'ansible/uspeak.service'
      dest: /etc/systemd/system/
  - name: clone portal repo
    git:
      repo: 'https://github.com/u-speak/portal.git'
      dest: /opt/portal
  - name: restart service
    systemd:
      state: restarted
      daemon_reload: yes
      name: uspeak
  - name: copy nginx config
    copy:
      src: 'ansible/nginx.conf'
      dest: /etc/nginx/
  - name: restart nginx
    systemd:
      state: restarted
      name: nginx
  - name: enable nginx
    systemd:
      name: nginx
      enabled: yes
  - name: enable uspeak
    systemd:
      name: uspeak
      enabled: yes
