---
- hosts: nodes
  gather_facts: no
  remote_user: root
  vars:
      LOG_FORMAT: 'json'
  vars_prompt:
    - name: VERSION
      prompt: 'Enter version of binary to deploy'
      default: 'v0.0.1'
  tasks:
  - name: create deployment directory
    file:
      path: /opt/uspeak
      state: directory
  - name: download the latest uspeakd binary
    get_url:
      url: 'https://github.com/u-speak/uspeakd/releases/download/{{VERSION}}/uspeakd-{{VERSION}}-linux-amd64'
      dest: /opt/uspeak/uspeakd
      mode: 0755
  - name: write config file
    template:
      src: ansible/config.yml.j2
      dest: /opt/uspeak/config.yml
